### ISSUE TITLE
Engine conflict issue

### ISSUE THREAD

**Issue by ilanbiala** [hueniverse/hawk#126]
```
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
```

I require ~0.10.30 in my package.json, and many other people who develop private things probably don't care to work with a 0.8 instance. You can still support it by all means, but I wish it wouldn't output all the warnings in the console.

By the way, this issue seems to be present across a lot of packages you work on (hawk, sntp, hoek, cryptiles, boom), can you fix it in those places too?

**Comment by framerate** [comment]
This has been on my radar for a while as well. Can I get some info to WHY we have dependencies requiring 0.8x?

I tracked it down to my application using `requestjs`, which in turn uses `hawk`. Trying to get our install down to no errors/warnings so new guys stop asking me haha :)

Thanks for any info you can provide!
