### ISSUE TITLE
Java Implementation of Hawk

### ISSUE THREAD

**Issue by mcdee** [hueniverse/hawk#13]
I'm working on a Java implementation of Hawk.  Currently appears to be compliant with 0.1.0.

The repository is at https://github.com/wealdtech/hawk

**Comment by TanimKhan** [comment]
Is this java implementation updated with this https://github.com/hueniverse/hawk version?

**Comment by mcdee** [comment]
@TanimKhan no; it remains at an earlier version.  Feel free to update it as required and submit a PR.
