### ISSUE TITLE
[browser] How to sign a FormData value?

### ISSUE THREAD

**Issue by haf** [hueniverse/hawk#133]
In browser.js, if I'm sending a `multipart/form-data`, how do I sign it? I don't want to base64 serialise the request.

![screen shot 2015-01-07 at 14 05 48](https://cloud.githubusercontent.com/assets/193115/5645950/75aa8814-9676-11e4-94d9-41a2198d34f9.png)

Just passing it along gives this:

![screen shot 2015-01-07 at 14 07 12](https://cloud.githubusercontent.com/assets/193115/5645955/89c4f384-9676-11e4-8b02-9237ef54b2b0.png)

**Comment by hueniverse** [comment]
The protocol doesn't care. You need to somehow get a hash of the payload or just don't use that feature. There are limits to what we can do with payload security. I would simply avoid making security assumption on these payloads and protect them via other means (e.g. combine hawk with TLS).
