### ISSUE TITLE
Question: Is it very much like one-legged OAuth 1.0a?

### ISSUE THREAD

**Issue by brutuscat** [hueniverse/hawk#134]
Hi, I wonder what are the differences between hawk and a "one-legged" OAuth 1.0a? http://oauthbible.com/#oauth-10a-one-legged

**Comment by hueniverse** [comment]
There is no such thing as one legged. The legs are not steps but parties involved so whoever wrote that just doesn't understand the terminology.

As for the difference, this is a simpler, cleaner, and more suitable for modern platforms than the original 1.0a signature method which was designed to support stuff like PHP4.
