### ISSUE TITLE
Audit status by version

### ISSUE THREAD

**Issue by Dynom** [hueniverse/hawk#144]
Hi,

I'm curious to learn if any external audits have been done on the Hawk implementation(s) and possibly client libraries. I've read through the source and find little points of interest, but I'm no security expert by far. I think that this would be a valuable addition to this project.

**Comment by hueniverse** [comment]
It has been informally reviewed by many experts. Mozilla chose it as the foundation of their identity APIs. Beyond that you would need to get your own expert review.
