### ISSUE TITLE
Questions about Best Practices

### ISSUE THREAD

**Issue by hsilverstein** [hueniverse/hawk#149]
I am new to this type of authentication and wanted to ask a couple of questions for clarification. I'm sorry if this isn't the right place to do so. I realize my questions may be extremely basic, but I'm trying to fully understand the scheme and how it functions. I've been reading through the source code and taking notes, but my questions mostly have to do with best practices.

I want to build an API that will be consumed by a web server and the web browser. The API and web server are separate hapi applications and will live at `api.example.com` and `www.example.com` respectively. The web browser uses a JavaScript-based single page application to make AJAX requests. All questions will assume this structure.

![setup](https://cloud.githubusercontent.com/assets/14972213/10422657/465ab9b8-708b-11e5-9927-24d0f07bd70e.png)

**Question 1**:

Is the shared symmetric key similar to a session id?

After a user logs into my website, would it make sense for the API send back the shared key in the response? If so, is that what's stored in the client? Is it safe to store that as a plain text in local storage, for example? If I understand correctly, it will be needed to calculate MACs for requests, especially if they're using replay protection.

**Question 2**:

(Note: I'm calling them auth details, because I'm not sure what I'm storing on the client yet. See the first question.)

I've read in previous issues that you'd recommend storing Hawk auth details in local storage rather than cookies. This works fine for the web browser because I can just pull the string out of local storage and put it in the header of each AJAX request. However, I'm not quite sure how to handle it in regards to my web server.

When a user lands on any page, e.g. - `www.example.com/pages/1`, the web server calls the API to get data, renders an HTML template, and then sends the full HTML page to the web browser. After that, the web browser's SPA takes over and makes API requests and renders out HTML using JavaScript.

What would be the recommended way to send the web server the details in this situation? Since the Hawk auth details aren't store in a cookie and the web server doesn't have access to local storage, I'm not sure how to send that information. The web server is only used for the initial landing, but I still need that information to authenticate certain portions of the site.

**Question 3**:

I read the article on your personal blog about securing web session ids and I noticed that many of the principles you listed are implemented in the Hawk scheme. In the article, you state that adding an expiration to the credentials allows the server to avoid database calls for expired tokens.

I've seen around the internet that people use schemes, such as JWT, to avoid making database calls entirely. This seems insecure to me because it removes the ability to revoke a token at any given time. It seems to me that if you want your system to be secure, you should be doing a database look up on any seemingly valid request.

I just wanted clarification on what the article was saying. Were you saying that you should almost never make a database call, as recommended by JWT, or were you saying that you can avoid database calls only when you know the token is invalid beforehand, e.g. - when it's expired?

Would it even be appropriate to add something like an expiry with Hawk or is that more for traditional cookie-based session id schemes? I noticed expiration isn't part of the default set of keys for Hawk, but it is for Oz. Would Oz be more appropriate for my use case?

**Question 4**:

I'm trying to wrap my head around the replay protection. It says the nonce is unique for each key and time stamp combination, making the request valid for a short period of time. If the client is out of sync with the servers time, e.g. - within a web browser, the server provides the client with a time stamp to calculate an offset.

When it comes to the web browser, does this mean you should take the time stamp from the server and subtract `Date.now()` from it to get the offset, then apply that offset to any time stamp used for a Hawk request? It's simple, but I just wanted to make sure I was understanding it correctly.

For example, if the offset was calculated to be -100ms, would I just simply subtract 100ms from each time stamp when I make the request and calculate a MAC?

This would also be a candidate for skipping a database look up, correct? I'm looking through the source and it seems like the nonce and time stamp are calculated into the MAC, making it resistant to tampering, which means you can just ignore the request if it's out of bounds.

**Question 5**:

This actually ties in a bit with the third question, but I figured I should ask it separately. At the moment, the API server, the web server, and the single-page application are all owned by me. Eventually, I would like to open up the API for use to third-parties.

Would it make sense to use Oz from the get-go? It would seem a bit strange to treat my own web server and single-page application as a third-party. It was my understanding the Hawk was made for use cases in which all resources are own by the same person and Oz was meant to be used once third-parties become involved.

Since my current goals parallel the idea of user sessions, which typically have some sort of expiration period, I wasn't sure if Hawk was appropriate or not. I was confused because Hawk doesn't seem to have an expiration while Oz provides that as part of its core features. Are either Hawk or Oz appropriate what what essentially amounts to a user session?

**Comment by hueniverse** [comment]
I can't help you make most of these decisions as you need to understand the trade offs yourself and the risks with every design decision. I also don't have the time to answer this long list at this time. What I can suggest is to look at the [postmile](https://github.com/hueniverse/postmile) project and see how it does something very similar. The code there is using an older version of Oz but it still works the same today.
