### ISSUE TITLE
What does "Holk" mean?

### ISSUE THREAD

**Issue by thebinarypenguin** [hueniverse/hawk#150]
In the repo's description "HTTP Holk Authentication Scheme" what does "Holk" mean?

**Comment by gergoerdosi** [comment]
It's the old name of the module: https://github.com/hueniverse/hawk/commit/410ade718a35d4ad22f1dc7fb369d65a19902d2a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by thebinarypenguin** [comment]
Oh okay. Someone should probably fix that description then.

**Comment by hueniverse** [comment]
Holder of Key.

**Comment by gergoerdosi** [comment]
@hueniverse I think the description still needs to be fixed.

<img width="269" alt="screen shot 2015-10-18 at 20 19 23" src="https://github-cloud.s3.amazonaws.com/assets/371149/10565630/b3b0465a-75d5-11e5-97f2-5b8be1855512.png">
