### ISSUE TITLE
Version dependency issue for 0.10.

### ISSUE THREAD

**Issue by ErisDS** [hueniverse/hawk#157]
Hawk `3.1.0` states it has support for engines `"node": ">=0.10.32"`

Hawk 3.1.0 depends on boom `^2.8.x`

Because (I think) of the combo of the caret and the x in `^2.8.x`, on certain versions of 0.10.x, boom 3.0.0 is installed instead of 2.8.0.

Boom `3.0.0 `has been upgraded to only support node `4.0.0` and uses the new `const` syntax, and therefore causes an error.

This problem has trickled up to [request](https://github.com/request/request/issues/1921). I was able to reproduce this for node 0.10.13 and there is a similar issue open for request for 0.10.5: https://github.com/request/request/issues/1452. I realise these are very old versions, but it seems to me that support has been dropped accidentally due to changes inside dependencies.

Would it perhaps be possible to get a 3.1.1 release which targets 2.8.0 without the caret?

**Comment by rutaihwa** [comment]
Probably this is what I'm also [ experiencing](https://github.com/hapijs/boom/issues/87)
