### ISSUE TITLE
Client build usage with webpack

### ISSUE THREAD

**Issue by jeduan** [hueniverse/hawk#158]
I'm trying to use Hawk with webpack, however, the build fails because it's trying to import both `dns` and `dgram`.

I manually changed the required file to be `dist/client.js`, but that fails when trying to require `./utils` and `./crypto`. Changing the required file to `lib/client.js` fixes that, but requiring `./utils` requires `sntp` which requires `dns` and `dgram` so we come full circle.

Manually changing the required file to `lib/browser.js` does make everything work, but it took some time before I figured that out, so I'm sharing this in case someone stumbles upon this.

**Comment by hueniverse** [comment]
@kpdecker any ideas?

**Comment by kpdecker** [comment]
https://github.com/hueniverse/hawk/commit/4fc847c448077af21d48d5686de786c073610646#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34 Should be `lib/browser.js` and `dist/browser.js`. 

https://github.com/hueniverse/hawk/commit/4fc847c448077af21d48d5686de786c073610646#diff-215b25d5bf5c0b4623ad1a2b62456f60R3 should require `dist/browser.js`

**Comment by jeduan** [comment]
Just ran @kpdecker's changes and I can confirm they fix the build. Also, they fix usage in Safari which is currently broken due to the use of `const`.
(error is `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`)

**Comment by hueniverse** [comment]
@jeduan I'll take a PR.
