### ISSUE TITLE
Where to store app-credentials in angular application?

### ISSUE THREAD

**Issue by platdesign** [hueniverse/hawk#162]
Hey,
i would like to use hawk between a hapi-api and an angular app.
Correct me if im wrong, but to get an app-ticket the angular-app needs its' app-credentials in the browser. Is this the "right" way? In this case everyone could see/get the app-credentials.

**Comment by hueniverse** [comment]
There is no way to authenticate an application. Typically, you would use hawk in association with some logged in user or other application state (cookies, etc.). There are many different strategies depending on what you are protecting.

**Comment by platdesign** [comment]
So the following flow would be the right way to do it? (using oz for authorization)

![bildschirmfoto 2016-01-03 um 08 07 34](https://cloud.githubusercontent.com/assets/4584887/12077675/19fae27e-b1f1-11e5-9335-d537c20377b8.png)

**Comment by hueniverse** [comment]
I can't really follow this diagram. There are a lot of important details to get right and they change for each use case. Unfortunately, I am not in a position to help people with their security architecture. My modules are meant as building blocks for people who understand how this stuff works.
