### ISSUE TITLE
No browser.js when using Bower

### ISSUE THREAD

**Issue by shawm11** [hueniverse/hawk#167]
I see that the lib directory is ignored in the bower.json file. Because the lib directory is ignore, I do not get the lib/browser.js file. I am using Hawk in a regular web application, not a Node project. Adding "!lib/browser.js" back into the ignore list in the bower.json file would fix this issue.

**Comment by hueniverse** [comment]
I know nothing about bower. If you make a PR and someone else can confirm I'll merge.
