### ISSUE TITLE
Would you consider backporting #168 to 3.x?

### ISSUE THREAD

**Issue by jakubpawlowicz** [hueniverse/hawk#169]
Some packages (like https://github.com/request/request) are stuck on hawk 3.x because of node.js 4 dependency, and the recently fixed security issue still applies to them. Any chances to see 3.1.3 with backported 0833f99ba64558525995a7e21d4093da1f3e15fa?

**Comment by landau** [comment]
+1

I could use this bug fix as well. My services are not quite ready for node 4.

**Comment by hueniverse** [comment]
It doesn't affect request users. These issues are only possible on the server, not the client side of the protocol. If someone else does the work I'll consider it. See #170

**Comment by jakubpawlowicz** [comment]
Thanks @hueniverse and @remy!
