### ISSUE TITLE
Normalized request method

### ISSUE THREAD

**Issue by itafroma** [hueniverse/hawk#180]
Out of curiosity, I was wondering what the purpose of [normalizing the request method to uppercase](https://github.com/hueniverse/hawk/blob/master/lib/crypto.js#L70) was, considering RFC 2616 / RFC 7231 state the [request method is case-sensitive](https://tools.ietf.org/html/rfc7231#section-4.1). Is it to accommodate "broken" HTTP servers that incorrectly accept case-insensitve request methods?

**Comment by hueniverse** [comment]
It's to deal with broken developers.

**Comment by itafroma** [comment]
Thanks for the answer, I appreciate it! Makes sense.
