### ISSUE TITLE
Question: Viable C/C++ Port of this available?

### ISSUE THREAD

**Issue by dealproc** [hueniverse/hawk#185]
Looking at using Hawk for an embedded device solution, and was wondering if there's an embedded c/c++ version of the tools available.  If not, is there a good place to start?

**Comment by hueniverse** [comment]
https://github.com/hueniverse/hawk/issues/91

**Comment by dealproc** [comment]
I ignored this library as it states it's for the server-side signing, but didn't seem to mention enough capability for use with client-side cases.

Will re-review the code (again) and see if maybe the readme is false as compared to the code itself.  Will probably need a chat with the author to understand what state the code is in.
