### ISSUE TITLE
Use of const in strict mode??

### ISSUE THREAD

**Issue by tayaggerald2509** [hueniverse/hawk#188]
const Hoek = require('hoek');
^^^^^
SyntaxError: use of const in strict mode.

**Comment by landau** [comment]
Latest Hawk demands node >= 4 which is es6 compatible. Are you using < 4?

https://github.com/hueniverse/hawk/blob/master/package.json#L15-L17

**Comment by hueniverse** [comment]
https://github.com/request/request/issues/2831
