### ISSUE TITLE
Update README.md usage example

### ISSUE THREAD

**Issue by Dreyer** [hueniverse/hawk#197]
I was going to send you a pull request after I updated the [`README.md`](https://github.com/hueniverse/hawk/blob/master/README.md#usage-example) usage examples inline with the ES6 syntax you're using in [`example/usage.js`](https://github.com/hueniverse/hawk/blob/master/example/usage.js) but then I noted they are slightly different and I wasn't sure if that was on purpose or not.

**Comment by hueniverse** [comment]
They don't have to be the same.

**Comment by Dreyer** [comment]
OK. Should the `README.md` be updated with the ES6 syntax you're using throughout?

**Comment by hueniverse** [comment]
Sure.
