### ISSUE TITLE
Use of shorthand property in browser.js breaks non es2015 environments 

### ISSUE THREAD

**Issue by tkh44** [hueniverse/hawk#199]
https://github.com/hueniverse/hawk/blob/master/lib/browser.js#L97

**Comment by balupton** [comment]
Just ran into this updating some deps on our Bevry packages, which to this day, still support node 0.12 and most still supporting node 0.8, thanks to the use of:

- https://github.com/bevry/editions/wiki - publish multiple editions and use the correct one for the correct environment
- https://github.com/bevry/awesome-travis - compile the project on CI with the desired node version, but run it on the specified
