### ISSUE TITLE
sntp undefined

### ISSUE THREAD

**Issue by McPo** [hueniverse/hawk#200]
Hi,

Ive currently have hawk up and working (in electron+webpack), however I was hoping to add sntp support incase a clients clock is incorrect. However when accessing the hawk.sntp, it returns as undefined.

sntp is exported within lib/index.js and the main of the package is set to the lib/index.js. I have noticed that hawk.sntp is not defined within dist/browser.

I have tried both importing and requring hawk.

Any idea what might be the issue.

Thanks,
Emmet

**Comment by McPo** [comment]
The "solution" was to import 'hawk/lib/index' instead of just 'hawk'.

Also the docs fail to mention that Hawk.sntp.start() expects a callback in which the header should be generated in.

```
const hawk = require('hawk/lib/index');
	hawk.sntp.start(() => {
		..........
		const hawkHeader = hawk.client.header(options.url, options.method, { credentials: hawkCredentials });
		..........
	});
}

```

I also noticed that while HAWK request was working as expected with `const hawk = require('hawk');` . Authenticating the response always returned true. However when requiring with `const hawk = require('hawk/lib/index');` the response is correctly authenticated.

**Comment by hueniverse** [comment]
You can't use sntp in the browser. You need a UDP connection which is not available. This is why sntp is not available to you in the browser dist. Hawk has a way for the server to inform the client about clock skew and for the client to validate this information and then store it for future use. You can look at the test for `client.authenticate()` https://github.com/hueniverse/hawk/blob/master/test/browser.js#L915
