### ISSUE TITLE
[Q] Server time in response claritifcation

### ISSUE THREAD

**Issue by gardenia** [hueniverse/hawk#206]
Hi, 

this is just a quesiton and apologies in advance if I'm missing what may well be a simple/obvious point.

In the docs it says:

> When receiving a request with a bad timestamp, the server provides the client with its current time. The client must never use the time received from the server to adjust its own clock, and must only use it to calculate an offset for communicating with that particular server.

Can you please clarify in what way the server provides the client with the current time in that case?

I thought of 2 possibilities:
1] has this something to do with the Server-Authenticate header.  if so I can't see that component being added in the response header in the existing implementation/tests (but I may well be just missing it).
2] or does this just relate to the regular HTTP "Date" response header rather than anything specific to the Hawk protocol.

or is it some other option entirely?

Thanks.

**Comment by hueniverse** [comment]
It's in the www-authenticate header response.
