### ISSUE TITLE
Server-Authorization Wiki Example

### ISSUE THREAD

**Issue by bentonstark** [hueniverse/hawk#207]
I have implemented Hawk in my own https client implementation and everything is working so with unit tests derived from the Hawk wiki examples.  I have also integrated with a Hawk server that I did not author.  But I having trouble using the Hawk Wiki examples to validate the Server-Authorization response header mac in my unit tests.  

Does the example Hawk Server-Authorization example in the Hawk Wiki build on the previous client request example with all the same client values (host, HTTP verb, nonce, port, ts, url, HMAC key) except for the content hash and ext data which is transmitted back to the client from the server?  Or is the example not built upon the previous client example?

https://github.com/hueniverse/hawk#response-payload-validation

**Comment by hueniverse** [comment]
The examples are generated in the tests here:
https://github.com/hueniverse/hawk/blob/master/test/readme.js
