### ISSUE TITLE
Single URI Authorization: can't make it work :(

### ISSUE THREAD

**Issue by codekraft-studio** [hueniverse/hawk#209]
I'm using Auth0 and I'm following [this](https://auth0.com/blog/ten-things-you-should-know-about-tokens-and-cookies/#file-downloads) official guide for manage file downloads:

I've this situation (simplified):
```javascript
const credentials = {
  id: 'vaimo',
  key: 'some-secret',
  algorithm: 'sha256'
};

const credentialsFunc = function (id, callback) {

  return callback(null, {
    key: 'some-secret',
    algorithm: 'sha256'
  });

};

// Return the direct download url with generated bewit
router.post('/download', function(req, res) {
    var finalUrl = 'http://localhost:9000/api/shipments/download';
    var bewit = hawk.uri.getBewit(finalUrl, {
      credentials: credentials,
      ttlSec: (60 * 5) // 5 minutes
    });
    finalUrl = finalUrl + '?bewit=' + bewit;
    res.send(finalUrl);
  });

// Try to get the download, first validate the bewit
router.get('/download', function(req, res, next) {

    hawk.uri.authenticate(req, credentialsFunc, {}, function (err, credentials, attributes) {

      console.log(req.query); // dmFpbW9cMTQ5NDU5MDYzOFxvQXY1U2NRc3dFbzJxZ0NQcEpUTnlsTDFnSmxpT0J1Kzljd2ltYlIvazlJPVw
      console.log(attributes); // { mac: 'oAv5ScQswEo2qgCPpJTNylL1gJliOBu+9cwimbR/k9I=' }

      if (err) {
        return res.status(401).send(err);
      }

      next();

    });

  }, function(req, res) {

    res.send('here the file');

});
```

By posting (with auth0 access token) to /api/shipments/download I get the url with the bewit token, like this:
`http://localhost:9000/api/shipments/download?bewit=dmFpbW9cMTQ5NDU5MDYzOFxvQXY1U2NRc3dFbzJxZ0NQcEpUTnlsTDFnSmxpT0J1Kzljd2ltYlIvazlJPVw`

than I redirect to that url to start the download or whatever, but it fails in [this](https://github.com/hueniverse/hawk/blob/master/lib/server.js#L429-L441) lines, beucase the generated mac is different from mine.

Everytime I get 401 Bad Mac, since I'm pretty much following the examples, I don't get what i'm doing wrong.

I'm also trying to follow [this](https://github.com/hueniverse/hawk#single-uri-authorization) example of single URI authorization from your official guide.

Sorry for my bad english.

**Comment by AJamesPhillips** [comment]
@codekraft-studio the hawk example you linked to works fine for me.  I'd suggest you look at what `req` is that comes from "`router`" that you're passing to `hawk.uri.authenticate`.  This might be a related issue that might help you if you're using express https://github.com/hueniverse/hawk/issues/201#issuecomment-264050397

**Comment by codekraft-studio** [comment]
@AJamesPhillips How it should be the request object? I mean, it needs to have specific headers or something?

By the way I just watched at req and I think the problem is req.url is /download?bewit=... and as they explain in issue 201 it should be like originalUrl which is /api/shipments/download?bewit=... in my case.

By copying all of this (just to be sure), it's working:
```javascript
var request = {
     method: req.method,
     url: req.originalUrl,
     headers: req.headers,
     port: req.port,
     host: req.hostname
};
```

Many thanks.
