### ISSUE TITLE
new error with const

### ISSUE THREAD

**Issue by mirzazeyrek** [hueniverse/hawk#214]
This error message started to appear recently. Is there anything you guys suggest may be ? 

/node_modules/grunt-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
11:16:32 const Hoek = require('hoek');
11:16:32 ^^^^^
11:16:32 SyntaxError: Use of const in strict mode.
11:16:32     at exports.runInThisContext (vm.js:73:16)
11:16:32     at Module._compile (module.js:443:25)
11:16:32     at Object.Module._extensions..js (module.js:478:10)
11:16:32     at Module.load (module.js:355:32)
11:16:32     at Function.Module._load (module.js:310:12)
11:16:32     at Module.require (module.js:365:17)
11:16:32     at require (module.js:384:17)
11:16:32     at Object.<anonymous> (/var/jenkins/workspace/artbees-portal/pr/253/node_modules/grunt-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
11:16:32     at Module._compile (module.js:460:26)
11:16:32     at Object.Module._extensions..js (module.js:478:10)

**Comment by zhentian-wan** [comment]
The same problem

**Comment by mirzazeyrek** [comment]
@zhentian-wan 

for a possible solution please check my comment:

https://github.com/sass/node-sass/issues/2100#issuecomment-330881630

**Comment by majidpal** [comment]
Hi @mirzazeyrek - Can you help me what fixes were done? we are using node:0.12.7 image for building application.

**Comment by hueniverse** [comment]
https://github.com/request/request/issues/2831

**Comment by majidpal** [comment]
Thanks. How to use this? I am not able to pass ssl flag in run command
