### ISSUE TITLE
Server-Authorization incompatible with browser caching

### ISSUE THREAD

**Issue by LeviticusMB** [hueniverse/hawk#224]
We have a server application that uses *ETags* & status 304 to avoid sending the response bodies if the client already has a valid copy.

When now try to add the *Server-Authorization* header, it turns out that the browser clients fails to validate the server responses.

The reason for this is that when the server returns a (*Server-Authorization*-signed) 304 response, the browser returns the original response, *including all original headers* to the caller. The *Server-Authorization* header the client sees was thus signed with different *ts*, *nonce*, *app* & *dlg* params, and these values are no longer available to the client. Thus, when the client tries to validate the response, the *mac* is invalid and the response is rejected.

The only solution I can see is that the *Server-Authorization* header needs to include these missing parameters so the client can correctly validate responses that come from the browser cache.

Thoughts or suggestions?

**Comment by hueniverse** [comment]
Client has to be the one holding on to these parameters. If you trust whatever the server sends, that defeats the purpose of the protection allowing an attacker to reuse signed responses with random requests. You have a few options. First, if you use TLS, you can skip the server response validation in most cases. I don't know what you are protecting but if your client is a browser and you always use TLS, it is pretty safe to skip. Second, you can cache the etags you validated and check against that.

It is odd the Server-Authorization header is being echoed back on a 304 response. I wonder if that is correct /@mnot.

**Comment by mnot** [comment]
Is the 304 including a new header? If so, that's what will be seen by your code; otherwise, the "old" header will be used.

**Comment by hueniverse** [comment]
@LeviticusMB how do you generate the headers?

**Comment by LeviticusMB** [comment]
We already use TLS of course and we haven't used *Server-Authorization* until now, but we want to add it for various reasons, one being MITM attacks. Replay protection would be nice of course but it's more important for us that the response has not been tampered with.

Caching ETags would not be an acceptable solution. The cached responses come from the browser cache and we would have to keep all request params forever in this case. (It's just a normal XHR request via jQuery or Angular).

The 304 responses are signed with using the request params but this response never reaches the browser app. Same behavior in FF and Chrome. Safari doesn't use the cache at all in this case. Not sure why.

Here are some example requests:

### Initial request

```
GET /v1/~onslip.com/peripherals?s=name&c=100 HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: application/json
Accept-Language: sv,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost/~mb/BackOffice/
Authorization: Hawk id="pwd:mb@onslip.com", ts="1511343698", nonce="euNmoC", mac="vZI2wHrOO+GmWIy4JFgJql9Lrb0a2t7LxSXWy10t80o="
X-Requested-With: XMLHttpRequest
Cookie: _ga=GA1.1.2097347957.1468081252
DNT: 1
X-Forwarded-For: ::1
X-Forwarded-Host: localhost
X-Forwarded-Server: iris.local
Connection: Keep-Alive


HTTP/1.1 200 OK
Date: Wed, 22 Nov 2017 09:41:38 GMT
Server: Onslip Till Server, version [heads+feature+anti-dos-0-g594651e91]
Server-Authorization: Hawk mac="FpmZxvgzl9rFJjbkmrK4A31tvF3EwiTk5a1FKX7a+qs=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Cache-Control: private, max-age=0
X-Total-Count: 1
Vary: *
ETag: JUJR6rK7Z1VmHkwCeywOEmCvo5AUEQK/9f/BQDthNbkAoNnXMR04IgtSNxUOJWdZd
Content-Type: application/json
Content-Length: 160

[{"created":"2015-06-30T07:45:41.926Z","function":"kitchen-printer","name":"Kitchen","id":1,"updated-by":1,"device-id":"","updated":"2017-11-22T09:41:29.020Z"}]
```

The browser headers (via `console.log(jqXHR.getAllResponseHeaders());`):

```
Cache-Control: private, max-age=0
Connection: Keep-Alive
Content-Length: 160
Content-Type: application/json
Date: Wed, 22 Nov 2017 09:41:38 GMT
ETag: JUJR6rK7Z1VmHkwCeywOEmCvo5AUEQK/9f/BQDthNbkAoNnXMR04IgtSNxUOJWdZd
Keep-Alive: timeout=5, max=99
Server: Onslip Till Server, version [heads+feature+anti-dos-0-g594651e91]
Server-Authorization: Hawk mac="FpmZxvgzl9rFJjbkmrK4A31tvF3EwiTk5a1FKX7a+qs=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Vary: *
X-Total-Count: 1
```

### Second request

```
GET /v1/~onslip.com/peripherals?s=name&c=100 HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: application/json
Accept-Language: sv,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost/~mb/BackOffice/
Authorization: Hawk id="pwd:mb@onslip.com", ts="1511343789", nonce="kieblq", mac="OLmXwhg3U05GgrdAVgX9Ah4zFqZ0aCRnZlYkPFhH5Ew="
X-Requested-With: XMLHttpRequest
Cookie: _ga=GA1.1.2097347957.1468081252
DNT: 1
If-None-Match: JUJR6rK7Z1VmHkwCeywOEmCvo5AUEQK/9f/BQDthNbkAoNnXMR04IgtSNxUOJWdZd
X-Forwarded-For: ::1
X-Forwarded-Host: localhost
X-Forwarded-Server: iris.local
Connection: Keep-Alive



HTTP/1.1 304 Not Modified
Date: Wed, 22 Nov 2017 09:43:10 GMT
Server: Onslip Till Server, version [heads+feature+anti-dos-0-g594651e91]
Server-Authorization: Hawk mac="rCeMDaVzJal1+KUeUku+ncGUOLGNhFNUzu3cgoDNDZQ="
Cache-Control: private, max-age=0
Vary: *
```

The browser headers (via `console.log(jqXHR.getAllResponseHeaders());`):

```
Cache-Control: private, max-age=0
Content-Length: 160
Content-Type: application/json
Date: Wed, 22 Nov 2017 09:43:10 GMT
ETag: JUJR6rK7Z1VmHkwCeywOEmCvo5AUEQK/9f/BQDthNbkAoNnXMR04IgtSNxUOJWdZd
Server: Onslip Till Server, version [heads+feature+anti-dos-0-g594651e91]
Server-Authorization: Hawk mac="FpmZxvgzl9rFJjbkmrK4A31tvF3EwiTk5a1FKX7a+qs=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Vary: *
X-Total-Count: 1
```

**Comment by hueniverse** [comment]
What are you using on the server?

**Comment by mnot** [comment]
How are you capturing the requests and responses above?

The 304 should really update the stored response headers; It works with recent Firefox  (<https://www.mnot.net/blog/2017/03/16/browser-caching#validation>).

**Comment by LeviticusMB** [comment]
Oh my. The log was from `tcpflow` on the server port. In front of it, there was an Apache 2.4.27 server, which did indeed remove the *Server-Authorization* header [for 304 responses](http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.27/modules/http/http_filters.c?view=markup#l1488).

When I switched to an Nginx server and adjusted my code so that it sends the *hash* param even for 304 responses, all seems to be working just fine. Response and payload is validated for both un-cached and cached responses.

(Clients that *does* see the 304 response will use the hash to validate the request but otherwise ignore it, since they do not supply the payload to the `authenticate()` method. Acceptable and/or intended behavior?)

Updated protocol example (this time sniffed from the Nginx port) below. Thanks for all your help.

### First request

```
GET /v1/~onslip.com/peripherals?s=name&c=100 HTTP/1.1
Host: iris.local:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: application/json
Accept-Language: sv,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://iris.local:8080/BackOffice/
Authorization: Hawk id="pwd:mb@onslip.com", ts="1511434238", nonce="egpTB8", mac="JPn4MRm0ve4Q/800oqC/TRFbI3z5vJl4rvNd10xnTts="
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive


HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Thu, 23 Nov 2017 10:50:38 GMT
Content-Type: application/json
Content-Length: 160
Connection: keep-alive
Server-Authorization: Hawk mac="O9jy1enkHy64kaw4rwcnUoV3B71vfrwLZ5QcRmjP1ME=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Cache-Control: private, max-age=0
X-Total-Count: 1
Vary: *
ETag: JDuwjHucvC0l7b6oKIusxb1bH1oXPtQfXNBK/t7fyS7apl+XOwQ/gq3mClbyNI7hH

[{"created":"2015-06-30T07:45:41.926Z","function":"kitchen-printer","name":"Kitchen","id":1,"updated-by":1,"device-id":"","updated":"2017-11-22T09:41:29.020Z"}]
```

Browser headers:

```
Cache-Control: private, max-age=0
Connection: keep-alive
Content-Length: 160
Content-Type: application/json
Date: Thu, 23 Nov 2017 10:50:38 GMT
ETag: JDuwjHucvC0l7b6oKIusxb1bH1oXPtQfXNBK/t7fyS7apl+XOwQ/gq3mClbyNI7hH
Server: nginx/1.12.2
Server-Authorization: Hawk mac="O9jy1enkHy64kaw4rwcnUoV3B71vfrwLZ5QcRmjP1ME=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Vary: *
X-Total-Count: 1
```

### Second request

```
GET /v1/~onslip.com/peripherals?s=name&c=100 HTTP/1.1
Host: iris.local:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: application/json
Accept-Language: sv,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://iris.local:8080/BackOffice/
Authorization: Hawk id="pwd:mb@onslip.com", ts="1511434242", nonce="S6kX53", mac="4gkSZXInZ9ILShSPIkcX3UYOpEDf1JAx0Vq6jy2iwGI="
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
If-None-Match: JDuwjHucvC0l7b6oKIusxb1bH1oXPtQfXNBK/t7fyS7apl+XOwQ/gq3mClbyNI7hH


HTTP/1.1 304 Not Modified
Server: nginx/1.12.2
Date: Thu, 23 Nov 2017 10:50:42 GMT
Connection: keep-alive
Server-Authorization: Hawk mac="ZmuPZOO7csg5SMqpPc379m7/YHv8BQ+SQqQYdQsuAJ0=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Cache-Control: private, max-age=0
Vary: *
```

```
Cache-Control: private, max-age=0
Content-Length: 160
Content-Type: application/json
Date: Thu, 23 Nov 2017 10:50:42 GMT
ETag: JDuwjHucvC0l7b6oKIusxb1bH1oXPtQfXNBK/t7fyS7apl+XOwQ/gq3mClbyNI7hH
Server: nginx/1.12.2
Server-Authorization: Hawk mac="ZmuPZOO7csg5SMqpPc379m7/YHv8BQ+SQqQYdQsuAJ0=", hash="crcZyKP87VvRyf9bsDZBBJfThhjqTBglCWaI8k4gvEE="
Vary: *
X-Total-Count: 1
```

**Comment by mnot** [comment]
Interesting! Are you saying that Apache in reverse proxy mode was removing headers from a 304? if so, that's a bug (and I'll report it, unless you want to).

**Comment by LeviticusMB** [comment]
Yes, exactly. The updated *Server-Authorization* is stripped away and therefore the original header is included as part of the cached XHR response.

Would be great if you could report it and push for a fix, since Apache is so widely available.

**Comment by mnot** [comment]
Good. Are you using `mod_cache`? I *think* that's where the problem is.

**Comment by mnot** [comment]
It turned out to be in Apache's core HTTP handling. Filed:
  https://bz.apache.org/bugzilla/show_bug.cgi?id=61820

**Comment by LeviticusMB** [comment]
Awesome. Thanks!
