### ISSUE TITLE
Protocol example is insufficient

### ISSUE THREAD

**Issue by eproxus** [hueniverse/hawk#225]
The protocol example hashes the following request string:

```
hawk.1.header
1353832234
j4h3g2
GET
/resource/1?b=1&a=2
example.com
8000

some-app-ext-data
```

Nowhere is there a full list of what each line means. I suspect `example.com` is the host the request is being sent to and `8000` is the port, but it is not outlined anywhere. In the FAQ it is specified that the code is the specification, but the link it is pointing to is dead: https://github.com/hueniverse/hawk/blob/master/hueniverse/hawk/tree/master/lib

Please provide a fully documented example and/or at least point to the correct reference implementation.

**Comment by hueniverse** [comment]
You could have been a bit less lazy and figure out that the code was right there in the /lib folder...

**Comment by eproxus** [comment]
Agree, in the end I managed to find the code. You could have been a bit less lazy and specified the hashing procedure in text instead of in JavaScript code 😉

**Comment by hueniverse** [comment]
I don't find your comment funny.
