### ISSUE TITLE
Babel translation is picked up even when ignored

### ISSUE THREAD

**Issue by mathieudevos** [hueniverse/hawk#227]
Hello,

Not sure if this a hawk specific issue, but as this is a npm module, I believe it should not have any babel related files in its repo.

This issue is only applying to hawk as far as I can see from our repo.

Basically we have our src folder in our repo, and our dist repo (uncommitted). The build server runs yarn in the src folder, runs all unit tests inside of it. 
If this completes it runs babel translation with the following .babelrc

```
{
  "ignore": [
    "node_modules",
    "test"
  ],
  "plugins": [
    "transform-async-to-generator",
    "transform-runtime"
  ],
  "presets": ["es2015"]
}
```

However, taking a look in my build server, I can see the following log:

```
src/folder1/handler.js -> dist/folder1/handler.js
src/folder2/handler.js -> dist/folder1/handler.js
...
src/node_modules/hawk/client.js -> dist/node_modules/hawk/client.js
src/node_modules/hawk/dist/browser.js -> dist/node_modules/hawk/dist/browser.js
src/node_modules/hawk/lib/browser.js -> dist/node_modules/hawk/lib/browser.js
src/node_modules/hawk/lib/client.js -> dist/node_modules/hawk/lib/client.js
src/node_modules/hawk/lib/crypto.js -> dist/node_modules/hawk/lib/crypto.js
src/node_modules/hawk/lib/index.js -> dist/node_modules/hawk/lib/index.js
src/node_modules/hawk/lib/server.js -> dist/node_modules/hawk/lib/server.js
src/node_modules/hawk/lib/utils.js -> dist/node_modules/hawk/lib/utils.js
...
src/folder_last/index.js -> dist/folder_last/index.js
```

Would it be possible to update the NPM module in such a way that hawk no longer is being babel translated after runtime? Hawk is required because of request, so I have to "run with it".

BR,
Mathieu

**Comment by hueniverse** [comment]
I am sorry this is causing issues but I am not going to do anything about it. Also see: https://github.com/request/request/issues/2831.
