### ISSUE TITLE
Babel config duplicated in package.json

### ISSUE THREAD

**Issue by ukch** [hueniverse/hawk#228]
https://github.com/hueniverse/hawk/blob/4be11d0a81c6e258f2a5cf2a3d88370b8c92b995/package.json#L33

It seems to me that this duplication is here by mistake, as a more up-to-date config (eg. using `babel-preset-env`) appears in `.babelrc`.

An unintended consequence of this config being here is that attempting to babel compile this module (eg. as part of a dependent module) causes the error `Module build failed: Error: Couldn't find preset "es2015" relative to directory`

**Comment by piranna** [comment]
When will this be published on npm?

**Comment by hueniverse** [comment]
next few days.

**Comment by piranna** [comment]
Ok, thank you :-) After that, time to update [request](https://github.com/request/request) so we can erradicate the dependency :-)
