### ISSUE TITLE
Please consider a v6.x branch to patch security vulnerabilities

### ISSUE THREAD

**Issue by brkattk** [hueniverse/hawk#240]
I have [a branch](https://github.com/brkattk/hawk/tree/hotfix-hoek) that fixes [a security vulnerability in older versions of hoek](https://nodesecurity.io/advisories/566). Could you please consider making a branch off the `v6.0.2` tag so that I can make a PR into that? This way a newer version of 6.x can be released and packages like `request` can simply patch a version rather than update to radically new syntax. I'd be willing to help out wherever possible.

For reference:
https://github.com/request/request/issues/2874
https://github.com/request/request/pull/2875

**Comment by hueniverse** [comment]
There is no need. v6.0.2 already lists '4.x.x'.

**Comment by brkattk** [comment]
apologies for the non issue. I looked a little deeper and hoek's version is defined as `4.x.x` in `6.0.2` of hawk, and also all of it's deps. however, for some reason, instead of installing the latest, `4.2.1`, npm keeps installing `4.2.0`.
