### ISSUE TITLE
Hoek dependency allows prototype pollution

### ISSUE THREAD

**Issue by ambiguities** [hueniverse/hawk#242]
https://nodesecurity.io/advisories/566
Recommended to update hoek to > 4.2.0 < 5.0.0 || >= 5.0.3

**Comment by zdrawku** [comment]
@ambiguities did you managed to update hoek? I am experiencing "potential security vulnerability" warning in a [repo](https://github.com/IgniteUI/igniteui-docfx/network/dependencies).
