### ISSUE TITLE
Another PHP Port

### ISSUE THREAD

**Issue by shawm11** [hueniverse/hawk#243]
I have completed a PHP port of Hawk.

- Github: <https://github.com/shawm11/hawk-auth-php>
- Packagist: <https://packagist.org/packages/shawm11/hawk-auth>

This Hawk port was designed to be used by the [Oz PHP port](https://github.com/shawm11/oz-auth-php) (currently in beta). However, it can be used as a standalone package if you only need Hawk.

I also focused on making the API simple and similar to the original JavaScript Hawk API. So, if you are familiar with the JavaScript version of Hawk, you should not have a problem using this PHP port of Hawk.

If you find any bugs or have questions, open an issue on the [Github repository for this PHP port](https://github.com/shawm11/hawk-auth-php).

Side Note: I also created a [PHP port of Iron](https://github.com/shawm11/iron-crypto-php).

**Comment by hueniverse** [comment]
Nice!
