### ISSUE TITLE
Update cryptiles >4.1.2 to resolve security vulnerabilities

### ISSUE THREAD

**Issue by carlosscastro** [hueniverse/hawk#249]
Hello!

In some of the Microsoft Bot Framework repos have a dependency on request which has a dependency on hawk which depends on Cryptiles. We are getting a warning from a security vulnerability that would be solved upgrading cryptyles to >4.1.2.

Any idea how I can fix this vulnerability or plans to somehow upgrade cryptiles dependency?

Thanks!

**Comment by hueniverse** [comment]
You need to upgrade to the latest version of request which no longer has this dependency. I will not be publishing patches for old versions that are no longer supported.

**Comment by austince** [comment]
Hi! Thanks for addressing this. Which version was this updated in?
