### ISSUE TITLE
.NET Standard (.Net Core) implementation of Hawk

### ISSUE THREAD

**Issue by kinosang** [hueniverse/hawk#251]
Hi,

I have completed a .Net Standard port of Hawk.

Github: https://github.com/JoyMoe/HawkAuthentication
Nuget: https://www.nuget.org/packages?q=JoyMoe.HawkAuthentication

**Comment by hueniverse** [comment]
PHP?

**Comment by kinosang** [comment]
@hueniverse .Net (C#)

**Comment by hueniverse** [comment]
If you want to add this to the readme, just open a PR.
